ApprendeServer/urls.py
"""
    DEVELOP BY CARLOS BEDOY
    MOBILE AND WEB DEVELOPER
    carlos.bedoy@gmail.com
"""
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ApprendeServer.views.home', name='home'),
    # url(r'^ApprendeServer/', include('ApprendeServer.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
     url(r'^apprende/', include('manager.urls')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
"""
    DEVELOP BY CARLOS BEDOY
    MOBILE AND WEB DEVELOPER
    carlos.bedoy@gmail.com
"""
from django.conf.urls import url
from manager import views
urlpatterns = [


    url(r'^theme/get/$', 'manager.views.themes'),
    url(r'^user/get/$', 'manager.views.users'),
    url(r'^question/get/$', 'manager.views.questions'),
    url(r'^statistic/get/$', 'manager.views.statistics'),
    url(r'^course/get/$', 'manager.views.courses'),

    url(r'^user/get/'
        r'(?P<username>\w{0,50})/'
        r'(?P<password>\w{0,50})/$', 'manager.views.user_info'),

    url(r'^theme/get/'
        r'(?P<pk>\w{0,50})/$', 'manager.views.theme_from_course'),

    url(r'^user/add/'
        r'(?P<username>\w{0,50})/'
        r'(?P<password>\w{0,50})/'
        r'(?P<firstName>\w{0,50})/'
        r'(?P<lastName>\w{0,50})/'
        r'(?P<facebook>\w{0,50})/'
        r'(?P<twitter>\w{0,50})/'
        r'(?P<age>\w{0,50})$', 'manager.views.user_new'),

    url(r'^user_rank/get', 'manager.views.user_ranks'),

    url(r'^feed_by_user/get/'
        r'(?P<player_key>\w{0,50})/$', 'manager.views.feed_by_user'),

    url(r'^exam/get/'
        r'(?P<theme>\w{0,50})/'
        r'(?P<level>\w{0,50})/', 'manager.views.exam_theme_level'),

    url(r'^random_exam/get/'
        r'(?P<level>\w{0,50})/', 'manager.views.exam_random'),

    url(r'^user_rank/get', 'manager.views.user_ranks'),

    url(r'^feed/new/'
        r'(?P<level>\w{0,50})/'
        r'(?P<correct>\w{0,50})/'
        r'(?P<wrongs>\w{0,50})/'
        r'(?P<points>\w{0,50})/'
        r'(?P<course>\w{0,50})/'
        r'(?P<theme>\w{0,50})/'
        r'(?P<player>\w{0,50})/$', 'manager.views.feed_new'),


    url(r'^theme/new', views.ThemeCreate.as_view(), name='theme_new'),
    url(r'^user/new', views.UserCreate.as_view(), name='user_new'),
    url(r'^question/new', views.QuestionCreate.as_view(), name='question_new'),
    url(r'^course/new', views.CourseCreate.as_view(), name='course_new'),

    url(r'^theme/delete/(?P<pk>\d+)$', views.ThemeDelete.as_view(), name='theme_delete'),
    url(r'^course/delete/(?P<pk>\d+)$', views.CourseDelete.as_view(), name='course_delete'),
    url(r'^question/delete/(?P<pk>\d+)$', views.QuestionDelete.as_view(), name='question_delete'),

    url(r'^theme/edit/(?P<pk>\d+)$', views.ThemeEdit.as_view(), name='theme_edit'),
    url(r'^course/edit/(?P<pk>\d+)$', views.CourseEdit.as_view(), name='course_edit'),
    url(r'^question/edit/(?P<pk>\d+)$', views.QuestionEdit.as_view(), name='question_edit'),
    url(r'^user/edit/(?P<pk>\d+)$', views.UserEdit.as_view(), name='user_edit'),

    url(r'^theme/list', views.ThemeList.as_view(), name='theme_list'),
    url(r'^user/list', views.UserList.as_view(), name='user_list'),
    url(r'^question/list', views.QuestionList.as_view(), name='question_list'),
    url(r'^statistic/list', views.StatisticsList.as_view(), name='statistics_list'),
    url(r'^course/list', views.CourseList.as_view(), name='course_list'),

]

manager/models.py
from django.db import models

"""
    DEVELOP BY CARLOS BEDOY
    MOBILE AND WEB DEVELOPER
    carlos.bedoy@gmail.com
"""


class Course(models.Model):
    thumbnail = models.ImageField(upload_to='media/course_imgs/', default='media/course_imgs/None/no-img.jpg')
    name = models.CharField(max_length=45, help_text='name of course')
    description = models.TextField(max_length=100)
    popularity = models.FloatField()
    views = models.IntegerField()

    def __unicode__(self):
        return self.name


class Theme(models.Model):
    thumbnail = models.ImageField(upload_to='media/theme_imgs/', default='media/course_imgs/None/no-img.jpg')
    name = models.CharField(max_length=50, help_text='Algorithms')
    description = models.TextField(max_length=100, help_text='short description about theme')
    popularity = models.FloatField()
    views = models.IntegerField()
    course = models.ForeignKey(Course)

    def __unicode__(self):
        return self.name


class Question(models.Model):
    option_list = (
        (1, 'A)'),
        (2, 'B)'),
        (3, 'C)'),
        (4, 'D)'),
    )
    thumbnail = models.ImageField(upload_to='media/question_imgs/', default='media/question_imgs/None/no-img.jpg', null=True)
    question = models.CharField(max_length=250, help_text='Are you developer')
    answer1 = models.CharField(max_length=200, help_text='YES')
    answer2 = models.CharField(max_length=200, help_text='maybe')
    answer3 = models.CharField(max_length=200, help_text='why?')
    answer4 = models.CharField(max_length=200, help_text='Yes django music lol')
    correct = models.IntegerField(choices=option_list, help_text='correct answer :p')
    feedback = models.CharField(max_length=200, help_text='everythin')
    theme = models.ForeignKey(Theme)

    def __unicode__(self):
        return self.question


class User(models.Model):
    thumbnail = models.ImageField(upload_to='media/user_imgs/', default='media/course_imgs/None/no-img.jpg', null=True)
    username = models.CharField(max_length=45, help_text='for example carlos.bedoy@gmail.com')
    password = models.CharField(max_length=45, help_text='nomeacuerdo password')
    first_name = models.CharField(max_length=45, help_text='yesica', null=True)
    last_name = models.CharField(max_length=45, help_text='martinez', null=True)
    facebook = models.CharField(max_length=100, null=True, help_text='carlos.bedoy')
    twitter = models.CharField(max_length=100, null=True, help_text='@carlos_bedoy')
    age = models.IntegerField(help_text='you age lol', null=True)
    points = models.FloatField(help_text='how many points')
    plays = models.IntegerField(help_text='you are junior?')

    def __unicode__(self):
        return self.username


class Statistics(models.Model):
    level = models.IntegerField(help_text='quantity of questions')
    correct = models.IntegerField(help_text='number of corrects :D')
    wrongs = models.IntegerField(help_text='wrongs :(')
    points = models.FloatField(help_text='number of points')
    date = models.DateField(help_text='date created')
    player = models.ForeignKey(User)
    theme = models.ForeignKey(Theme)
    course = models.ForeignKey(Course)
    unicode(date)

    def __unicode__(self):
        return unicode(self.date)

manager/views.py
"""
    DEVELOP BY CARLOS BEDOY
    MOBILE AND WEB DEVELOPER
    carlos.bedoy@gmail.com
"""
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.db import connection
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from .models import *
from django.http import HttpResponse
from django.core import serializers
from datetime import datetime
from django.utils import simplejson



def themes(request):
    data = Theme.objects.select_related().order_by('course')
    json = serializers.serialize('json', data)
    return HttpResponse(json, mimetype='application/json')


def courses(request):
    data = Course.objects.all()
    json = serializers.serialize('json', data)
    return HttpResponse(json, mimetype='application/json')


def users(request):
    data = User.objects.all().order_by('-points')
    json = serializers.serialize('json', data)
    return HttpResponse(json, mimetype='application/json')


def statistics(request):
    data = Statistics.objects.all()
    json = serializers.serialize('json', data)
    return HttpResponse(json, mimetype='application/json')


def questions(request):
    data = Question.objects.all()
    json = serializers.serialize('json', data)
    return HttpResponse(json, mimetype='application/json')


"""
    WEB SERVICES

"""


def feed_new(request, level, correct, wrongs, points, player, course, theme):
    current_player = User.objects.get(id=player)
    current_course = Course.objects.get(id=course)
    current_theme = Theme.objects.get(id=theme)
    data = Statistics(level=level, correct=correct, wrongs=wrongs,
                      points=points, date=datetime.now(), player=current_player,
                      course=current_course, theme=current_theme)
    response_data = [{}]
    if data.save():
        response_data[0]['status'] = 0
    else:
        response_data[0]['status'] = 1
    json = simplejson.dumps(response_data)
    return HttpResponse(json, mimetype='application/json')


def feed_by_user(request, player_key):
    data = Statistics.objects.filter(player=player_key)
    json = serializers.serialize('json', data)
    return HttpResponse(json, mimetype='application/json')


def user_info(request, username, password):
    data = User.objects.filter(username=username, password=password)

    json = serializers.serialize('json', data, indent=4)
    return HttpResponse(json, mimetype='application/json')


def user_new(request, username, password, firstName, lastName, facebook, twitter, age):
    data = User(username=username, password=password, firstName=firstName, lastName=lastName,
                facebook=facebook, twitter=twitter, age=age)
    data.save()
    json = serializers.serialize('json', data, indent=4)
    return HttpResponse(json, mimetype='application/json')


def exam_theme_level(request, theme, level):
    data = Question.objects.filter(theme=theme).order_by('?')[:level]
    json = serializers.serialize('json', data)
    return HttpResponse(json, mimetype='application/json')


def theme_from_course(request, pk):
    data = Theme.objects.filter(course=pk)
    json = serializers.serialize('json', data)
    return HttpResponse(json, mimetype='application/json')


def exam_random(request, level):
    data = Question.objects.order_by('?')[:level]
    json = serializers.serialize('json', data)
    return HttpResponse(json, mimetype='application/json')


def user_ranks(request):
    data = User.objects.order_by('points')
    reverse = data.reverse()
    json = serializers.serialize('json', reverse)
    return HttpResponse(json, mimetype='application/json')

"""

        WEP APP <3

"""


class QuestionList(ListView):
    model = Question


class UserList(ListView):
    model = User


class ThemeList(ListView):
    model = Theme


class CourseList(ListView):
    model = Course


class StatisticsList(ListView):
    model = Statistics


class QuestionCreate(CreateView):
    model = Question


class UserCreate(CreateView):
    model = User


class CourseCreate(CreateView):
    model = Course


class ThemeCreate(CreateView):
    model = Theme


class QuestionEdit(UpdateView):
    model = Question


class UserEdit(UpdateView):
    model = User


class ThemeEdit(UpdateView):
    model = Theme


class CourseEdit(UpdateView):
    model = Course


class QuestionDelete(DeleteView):
    model = Question


class CourseDelete(DeleteView):
    model = Course


class ThemeDelete(DeleteView):
    model = Theme

manager/templates/manager/course_confirm_delete.html
{% extends  "base.html" %}
{% block header%}Apprende - Course Delete ♦{% endblock %}
{% block content %}
<form method="post">{% csrf_token %}
    Are you sure you want to delete course: "{{ object }}" ?
    <input type="submit" value="OK" />
</form>
{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/course_form.html
{% extends  "base.html" %}
{% block header%}Apprende - New Course ♥{% endblock %}
{% block content %}

<form method="post"  class="basic-grey">
    <fieldset>
        {% csrf_token %}
        {% for object in form %}
            <div data-role="fieldcontain">
                 {{ object.errors }}
	             {{ object.label_tag  }}
                 {{ object  }}
            </div>
        {% endfor %}
        <div class="ui-body ui-body-a">
		<fieldset class="ui-grid-a">
				<div class="ui-block-a"><button type="reset" data-theme="d">Limpiar</button></div>
				<div class="ui-block-b"><button type="submit" data-theme="a">Añadir</button></div>
	    </fieldset>
		</div>
    </fieldset>
</form>

        <script >

    </script>

{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/course_list.html
{% extends  "base.html" %}
{% block header%}Apprende - Course List ♥{% endblock %}
{% block content %}
<center>
<table data-role="table" id="movie-table" data-mode="reflow" class="ui-responsive table-stroke">
			<thead>
				<tr>
					<th data-priority="1">#</th>
					<th data-priority="2">Name </th>
					<th data-priority="3">Description</th>
                     <th data-priority="8">Edit</th>
                     <th data-priority="8">Delete</th>
				</tr>
			</thead>
			<tbody>
     {% for o in object_list %}
        <tr>
           <th>{{o.id}}</th>
          <th>{{o.name}}</th>
          <td>{{o.description}}</td>
          <td><a href="{% url course_edit o.id %}" data-role="button" data-mini="true" data-icon="edit" data-iconpos="notext"></a></td>
          <td><a href="{% url course_delete o.id %}" data-role="button" data-mini="true" data-icon="delete" data-iconpos="notext">.</a></td>
        </tr>
    {% endfor %}
        <tbody>
    </table>

        <br>
<a href="{% url course_new %}" data-role="button" data-icon="plus" data-inline="true"  >New Course</a>
    </center>
{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/question_confirm_delete.html
{% extends  "base.html" %}
{% block header%}Apprende - Question Delete ♦{% endblock %}
{% block content %}
<form method="post">{% csrf_token %}
    Are you sure you want to delete Question: "{{ object }}" ?
    <input type="submit" value="OK" />
</form>
{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/question_form.html
{% extends  "base.html" %}
{% block header%}Apprende - New Question ♥{% endblock %}
{% block content %}

<form method="post"  class="basic-grey">
    <fieldset>
        {% csrf_token %}
        {% for object in form %}
            <div data-role="fieldcontain">
                 {{ object.errors }}
	             {{ object.label_tag  }}
                 {{ object  }}
            </div>
        {% endfor %}
        <div class="ui-body ui-body-a">
		<fieldset class="ui-grid-a">
				<div class="ui-block-a"><button type="reset" data-theme="d">Limpiar</button></div>
				<div class="ui-block-b"><button type="submit" data-theme="a">Añadir</button></div>
	    </fieldset>
		</div>
    </fieldset>
</form>

        <script >
            $(document).ready(function(){
                $('#id_question').              attr('placeholder', '2 días antes de después de pasado mañana ');
                $('#id_answer1').               attr('placeholder', 'hoy...);
                $('#id_answer2').               attr('placeholder', 'mañana...);
                $('#id_answer3').               attr('placeholder', 'Mañana...);
                $('#id_answer4').               attr('placeholder', 'ayer...);
                $('#id_feedback').              attr('placeholder', 'No te diremos la respuesta');
                $("label[for='id_question']").  text('Pregunta');
                $("label[for='id_answer1']").   text('Respuesta A)');
                $("label[for='id_answer2']").   text('Respuesta B)');
                $("label[for='id_answer3']").   text('Respuesta C)');
                $("label[for='id_answer4']").   text('Respuesta D)');
                $("label[for='id_correct']").   text('Correcta');
                $("label[for='id_feedback']").  text('Retroalimentacion');
                $("label[for='id_theme']").     text('Seleccione tipo');
            });
    </script>

{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/question_list.html
{% extends  "base.html" %}
{% block header%}Apprende - Question List ♥{% endblock %}
{% block content %}
<center>
<table data-role="table" id="movie-table" data-mode="reflow" class="ui-responsive table-stroke" border="1" style="border-color:#fff">
			<thead>
				<tr>
					<th data-priority="1">#</th>
					<th data-priority="2">Question </th>
					<th data-priority="3">Answer #1</th>
					<th data-priority="4">Answer #2</th>
					<th data-priority="5">Answer #3</th>
                    <th data-priority="6">Answer #4</th>
                    <th data-priority="7">Correct Answer</th>
                    <th data-priority="8">Feedback</th>
                    <th data-priority="9">Theme</th>
                     <th data-priority="10">Edit</th>
                     <th data-priority="11">Delete</th>
				</tr>
			</thead>
			<tbody>
				<tr>
				</tr>
                </tbody>
     {% for o in object_list %}
        <tr>
          <th>{{o.id}}</th>
          <th>{{o.question}}</th>
          <td>{{o.answer1}}</td>
          <td>{{o.answer2}}</td>
          <td>{{o.answer3}}</td>
          <td>{{o.answer4}}</td>
          <td>{{o.correct}}</td>
          <td>{{o.feedback}}</td>
          <td>{{o.theme}}</td>
          <td><a href="{% url question_edit o.id %}" data-role="button" data-mini="true" data-icon="edit" data-iconpos="notext"></a></td>
          <td><a href="{% url question_delete o.id %}" data-role="button" data-mini="true" data-icon="delete" data-iconpos="notext">.</a></td>
        </tr>
    {% endfor %}
        <tbody>
    </table>

        <br>
<a href="{% url question_new %}" data-role="button" data-icon="plus" data-inline="true"  >New Question</a>
    </center>
{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/statistics_list.html
{% extends  "base.html" %}
{% block header%}Apprende - Statistics List ♥{% endblock %}
{% block content %}
<center>
<table data-role="table" id="movie-table" data-mode="reflow" class="ui-responsive table-stroke">
			<thead>
				<tr>
					<th data-priority="1">#</th>
					<th data-priority="2">Level</th>
					<th data-priority="3">Corrects</th>
					<th data-priority="4">Wrongs</th>
					<th data-priority="5">Points</th>
                    <th data-priority="6">Date</th>
                    <th data-priority="7">Player</th>

				</tr>
			</thead>
			<tbody>
     {% for o in object_list %}
        <tr>
           <th>{{o.id}}</th>
          <th>{{o.level}}</th>
          <td>{{o.correct}}</td>
            <td>{{o.wrongs}}</td>
            <td>{{o.points}}</td>
            <td>{{o.date}}</td>
            <td>{{o.player}}</td>
          </tr>
    {% endfor %}
        <tbody>
    </table>

        <br>
    </center>
{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/theme_confirm_delete.html
{% extends  "base.html" %}
{% block header%}Apprende - Theme Delete ♦{% endblock %}
{% block content %}
<form method="post">{% csrf_token %}
    Are you sure you want to delete theme: "{{ object }}" ?
    <input type="submit" value="OK" />
</form>
{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/theme_form.html
{% extends  "base.html" %}
{% block header%}Apprende - New Theme ♥{% endblock %}
{% block content %}

<form method="post"  class="basic-grey">
    <fieldset>
        {% csrf_token %}
        {% for object in form %}
            <div data-role="fieldcontain">
                 {{ object.errors }}
	             {{ object.label_tag  }}
                 {{ object  }}
            </div>
        {% endfor %}
        <div class="ui-body ui-body-a">
		<fieldset class="ui-grid-a">
				<div class="ui-block-a"><button type="reset" data-theme="d">Limpiar</button></div>
				<div class="ui-block-b"><button type="submit" data-theme="a">Añadir</button></div>
	    </fieldset>
		</div>
    </fieldset>
</form>

        <script >

    </script>

{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/theme_list.html
{% extends  "base.html" %}
{% block header%}Apprende - Theme List ♥{% endblock %}
{% block content %}
<center>
<table data-role="table" id="movie-table" data-mode="reflow" class="ui-responsive table-stroke">
			<thead>
				<tr>
					<th data-priority="1">#</th>
					<th data-priority="2">Name </th>
					<th data-priority="3">Description</th>
                     <th data-priority="4">Edit</th>
                     <th data-priority="5">Delete</th>
				</tr>
			</thead>
			<tbody>
     {% for o in object_list %}
        <tr>
           <th>{{o.id}}</th>
          <th>{{o.name}}</th>
          <td>{{o.description}}</td>
          <td><a href="{% url theme_edit o.id %}" data-role="button" data-mini="true" data-icon="edit" data-iconpos="notext"></a></td>
          <td><a href="{% url theme_delete o.id %}" data-role="button" data-mini="true" data-icon="delete" data-iconpos="notext">.</a></td>
        </tr>
    {% endfor %}
        <tbody>
    </table>

        <br>
<a href="{% url theme_new %}" data-role="button" data-icon="plus" data-inline="true"  >New Theme</a>
    </center>
{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/user_form.html
{% extends  "base.html" %}
{% block header%}Apprende - New User ♥{% endblock %}
{% block content %}

<form method="post"  class="basic-grey">
    <fieldset>
        {% csrf_token %}
        {% for object in form %}
            <div data-role="fieldcontain">
                 {{ object.errors }}
	             {{ object.label_tag  }}
                 {{ object  }}
            </div>
        {% endfor %}
        <div class="ui-body ui-body-a">
		<fieldset class="ui-grid-a">
				<div class="ui-block-a"><button type="reset" data-theme="d">Limpiar</button></div>
				<div class="ui-block-b"><button type="submit" data-theme="a">Añadir</button></div>
	    </fieldset>
		</div>
    </fieldset>
</form>

        <script >

    </script>

{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}

manager/templates/manager/user_list.html
{% extends  "base.html" %}
{% block header%}Apprende - User List ♥{% endblock %}
{% block content %}
<center>
<table data-role="table" id="movie-table" data-mode="reflow" class="ui-responsive table-stroke">
			<thead>
				<tr>
					<th data-priority="1">#</th>
					<th data-priority="2">Username </th>
					<th data-priority="3">First Name </th>
					<th data-priority="4">Last Name</th>
					<th data-priority="5">Birthday</th>
                    <th data-priority="6">Age</th>
                    <th data-priority="7">Points</th>
                    <th data-priority="8">Plays
                     <th data-priority="9">Edit</th>
				</tr>
			</thead>
</tbody>
     {% for o in object_list %}
        <tr>
          <th>{{o.id}}</th>
          <th>{{o.username}}</th>
          <td>{{o.first_name}}</td>
          <td>{{o.last_name}}</td>
          <td>{{o.birthday}}</td>
          <td>{{o.age}}</td>
          <td>{{o.points}}</td>
          <td>{{o.plays}}</td>
          <td><a href="{% url user_edit o.id %}" data-role="button" data-mini="true" data-icon="edit" data-iconpos="notext"></a></td>
                  </tr>
    {% endfor %}
        <tbody>
    </table>

        <br>
<a href="{% url user_new %}" data-role="button" data-icon="plus" data-inline="true"  >New User</a>
    </center>
{% endblock %}
{% block footer%}Develop by Carlos Bedoy | PandaMobile ® 2014{% endblock %}